In [2]:
import numpy as np #kütüpheyi kullanabilmek için import etmeliyiz

In [4]:
a = np.arange(15).reshape(3, 5) #arange()metodu ile 0’dan 15’e kadar bir 
#dizi yaratıyoruz.reshape() metodu ile 3*5’lik bir matris şekillendirmiş oluyoruz.
a #oluşturduğumuz a array’ini görelim

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape #a’nın boyutları

(3, 5)

In [6]:
a.ndim #a’nın rankı

2

In [7]:
a.dtype #eleman türünü döndürmek istersek

dtype('int32')

In [8]:
a.size #a’nın eleman sayısı

15

In [9]:
type(a) #oluşturduğumuz a array’inin türünü görmek istersek

numpy.ndarray

# Array Oluşturma 

In [10]:
import numpy as np  #En basit haliyle bir numpy array oluşturalım.

b = np.array([1,2,3,4,5])
b


array([1, 2, 3, 4, 5])

In [11]:
import numpy as np #Elemanlarının hepsi 0 olan 3*4 array oluşturmamızı sağlar.

c = np.zeros((3,4))
c


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
import numpy as np #Elemanlarının hepsi 1 olan 3*3 array oluşturmamızı sağlar.

d = np.ones((3,3))
d


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
e = np.arange(10,70,10) #10’dan 70’e kadar olan sayıları 10’ar 10’ar arttırarak bir bir array oluşturur.
e


array([10, 20, 30, 40, 50, 60])

In [14]:
f = np.eye((3)) #3*3 bir birim matris oluşturmamızı sağlar.
f


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
g = np.arange(10) #Elemanları 0’dan 10’a kadar olan bir array oluşturmamızı sağlar.
g


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
h = np.linspace(0,2,9) #0 ile 2 arasında bu sayılarda dahil olmak üzere 9 sayı oluşturduk.
h


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
ı = np.ones((2,4))*5 #Elemanlarının hepsi 5 olan 2*4 bir array oluşturmamızı sağlar.
ı


array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [20]:
k = np.full((2,3),8) #Elemanları aynı olan array oluşturmak için full() metodunu da kullanabiliriz.(2,3) dizinin 
#boyutunu belirtirken, matrisin 8’lerden oluşmasını istedik.
k



array([[8, 8, 8],
       [8, 8, 8]])

In [47]:
l = np.random.randint(0,50,5)# 0 ve 50 arasında 5 tane rastgele sayı üret
l

array([ 1, 39, 36, 43,  1])

In [48]:
m = np.random.rand(5) #0 ile 1 arasında 5 random sayı üret.
m


array([0.8251616 , 0.137013  , 0.43805667, 0.5694103 , 0.59116609])

# Eleman Seçme

In [22]:
n_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12, 13 ,14])

n_array = n_array.reshape(3,5)#array’i 3*5 formatına getirdik

n_array


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [23]:
n_array[0] #array 1.satırına ulaşmak istersek

array([0, 1, 2, 3, 4])

In [24]:
n_array[0:2] #array 1.ve 2.satırını istersek

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
n_array[0][0] #array 1.satırın ilk elemanını yazdıralım

0

In [26]:
n_array[:,0] #ilk sütunu alalım

array([ 0,  5, 10])

In [27]:
n_array[:,0:2] #1.ve 2.sütunu alalım

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [28]:
n_array[2,3] 

13

In [29]:
n_array[::-1] ##bu ifade ile ters çevirmiş oluruz.

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

# Matematiksel İşlemler

In [31]:
numpy_array = np.array([[1,2,3], #yeni bir array oluşturduk
                       [4,5,6],
                       [7,8,9]])

print(numpy_array.sum()) #array elemanlarının toplamı


45


In [32]:
print(numpy_array.max()) #en büyük eleman

9


In [33]:
print(numpy_array.min()) #en küçük eleman

1


In [34]:
#axis = 1 : satırı alır
#axis = 0 : sütunları alır

print(numpy_array.sum(axis = 1)) #satırları toplamak için 


[ 6 15 24]


In [35]:
print(numpy_array.sum(axis = 0)) #sütunları toplamak için

[12 15 18]


In [37]:
num_array = np.array([[1,2],
                     [5,6]])
                       
print(num_array + num_array) #array toplamı


[[ 2  4]
 [10 12]]


In [38]:
print(num_array + 2) #bir array'e bir sayı ekleme

[[3 4]
 [7 8]]


In [39]:
print(num_array - num_array) #array’ler için çıkarma işlemi

[[0 0]
 [0 0]]


In [40]:
print(num_array * num_array) #array’ler için çarpma işlemi

[[ 1  4]
 [25 36]]


In [41]:
print(num_array * 3) #bir array’in bir sayıyla çarpımı

[[ 3  6]
 [15 18]]


In [42]:
print(num_array / num_array) #array’ler için bölme işlemi

[[1. 1.]
 [1. 1.]]


# Transpoz Bulma

In [43]:
list_array = np.array([[1,2],
                      [4,5],
                      [7,8]])
print(list_array.T)
#Matrislerin satırını sütun, sütunlarını satır yapmaya transpoz alma işlemi denir.Bir array’in transpozu  .T ile bulunur.

[[1 4 7]
 [2 5 8]]


# Matris Çarpımı

In [44]:
#a1 matrisinin kolon sayısı a2 matrisinin satır sayısına eşitse a1 x a2 çarpımı tanımlıdır.Bu koşul çarpma işlemi 
#için gerekli bir kısıtlamadır.Bu koşulu sağlamayan iki matris çarpılmaz.a1 (3,2) bir matrisken, a2 matrisi (2,2) matristir.
#Çarpım sonucunun (3,2) bir matris olmasını bekliyoruz.
a1 = np.array([[1,2],
               [2,0],
               [3,1]])                     

a2 = np.array ([[4,3],
                [1,2]])


print(np.dot(a1,a2))


[[ 6  7]
 [ 8  6]
 [13 11]]


# Matris Birleştirme

In [49]:
#Birleştirme işlemiyle, iki veya daha fazla matris içeriğini tek bir dizide birleştirebiliriz.
a3 = np.array([[1,2],
               [2,0],
               [3,1]])                     


In [52]:
print(np.concatenate([a3, a3], axis =0)) #Satıra göre birleştirmek istersek, satır = 0

[[1 2]
 [2 0]
 [3 1]
 [1 2]
 [2 0]
 [3 1]]


In [53]:
print(np.concatenate([a3, a3], axis =1)) #Sütuna göre  birleştirme yapmak istersek, sütun = 1

[[1 2 1 2]
 [2 0 2 0]
 [3 1 3 1]]
